apiVersion: v1
kind: Pod
metadata:
  name: data-copy
  namespace: rs1
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: my-volume
          mountPath: /data
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: dev-backup-claim
