apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: myaap
  namespace: rs1
spec:
  no_log: true

#  admin_password_secret: dev-admin-password
#  database:
#     database_secret: external-postgres-configuration-gateway

  controller:
    name: dev
    disabled: false
#     postgres_configuration_secret: external-postgres-configuration-controller

  hub:
    disabled: true
#    postgres_configuration_secret: external-postgres-configuration-hub

  eda:
    disabled: true
#    database:
#       database_secret: external-postgres-configuration-eda

  lightspeed:
    disabled: true
